### ISSUE TITLE
How to use windowed mode?

### ISSUE THREAD

**Issue by lnicola** [e-nguyen/e-nguyen#22]
### Is Something Broken?
- [x] Can run other Vulkan software and I can use the [Vulkano](https://github.com/vulkano-rs/vulkano) examples
- [x] Supported sound server installed such as PulseAudio on Linux

### Type of Support Being Sought
- [ ] Can program Rust and want to learn how to fix the problem and be a master of the git
- [ ] Honorable colleague, just point me to the right files
- [x] Willing to run diagnostics specific to my platform and test fixes
- [x] I need to think about my life

### Before you submit
- [x] Checked for duplicate issues and PR's related to my issue
- [x] Linked to any PR's and issues that looked related
- [x] Put a lot of support emoji's on PR's related to my issue

Windowed mode looks like below. How do I use it?

![image](https://user-images.githubusercontent.com/308347/55193578-0450aa00-51b0-11e9-92a3-fba46e0d7c6c.png)

```
[2019-03-28T21:17:25Z WARN  e_nguyen::ewin] No discrete device was found.
[2019-03-28T21:17:25Z INFO  e_nguyen::ewin] Using device: Intel(R) HD Graphics 530 (Skylake GT2) (type: IntegratedGpu)
```

Note how there's no message related to the audio source.

**Comment by knappador** [comment]
The settings window doesn't yet have settings because there's no variability yet.

The 'm' hotkey is configured to launch the mesmerizer.  Marking duplicate to #4  and closing.
